version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm i
      - run: npm test
      - run: npm run danger

workflows:
  version: 2
  test:
    jobs:
      - test